#!/usr/bin/env bash
SELF_DIR="$(dirname "$(readlink -f "$0")")"
export PATH="$SELF_DIR/usr/bin:$PATH"
export LD_LIBRARY_PATH="$SELF_DIR/usr/lib:$LD_LIBRARY_PATH"
exec "$SELF_DIR/usr/bin/openvpn-gui-linux" "$@"
